# Generated by Django 6.0.4 on 2026-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=8)),
                ('prefecture', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=150)),
                ('building_name', models.CharField(blank=True, max_length=150)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
